### ISSUE TITLE
csrf always returns a token

### ISSUE THREAD

**Issue by efenatuyo** [Aspectise/Roblox-Mass-Tools#1]
https://github.com/Aspectise/Roblox-Mass-Tools/blob/74e32a4193aa3845ee6ec43db083055a1db07071/src/csrf.py#L6
even if cookie is invalid a token will still be returned

**Comment by Aspectise** [comment]
> https://github.com/Aspectise/Roblox-Mass-Tools/blob/74e32a4193aa3845ee6ec43db083055a1db07071/src/csrf.py#L6
> 
> 
> even if cookie is invalid a token will still be returned

Whats the problem?

**Comment by efenatuyo** [comment]
There will be always a token returned so u don’t need to check if there is a token or not. Also you duped some parts you made another function where it also gets the xtoken just like here

**Comment by Aspectise** [comment]
> There will be always a token returned so u don’t need to check if there is a token or not. Also you duped some parts you made another function where it also gets the xtoken just like here

I know, that file has it own xcsrf, for some reason the xcsrf from the global csrf file doesn't work on it
